### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by Heclalava** [mrlongshen/blockpublictorrent-iptables#1]
Hi

I am curious in what environment you are using this script?

How effective is it at blocking torrents?

Will it effectively block torrents on a company proxy that employees need to first go through to access the internet?

Your response appreciated.

Thanks

EDIT: I have tested by placing this scipt on the proxy and tested by downloading a torrent as a test. I chose photoshop as I knew it would have a large seed base. Here is the magnet url:
magnet:?xt=urn:btih:89EBCCD43FA8F75F8439896EA5211EA60E041A4F&dn=Adobe%20Photoshop%20CC%202015%20(20150529.r.88)%20(32%2B64Bit)%20%2B%20Crack&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2F47.ip-51-68-199.eu%3A6969%2Fannounce

This torrent is still able to download despite your script.

**Comment by mrlongshen** [comment]
> Hi
> 
> I am curious in what environment you are using this script?
> 
> How effective is it at blocking torrents?
> 
> Will it effectively block torrents on a company proxy that employees need to first go through to access the internet?
> 
> Your response appreciated.
> 
> Thanks
> 
> EDIT: I have tested by placing this scipt on the proxy and tested by downloading a torrent as a test. I chose photoshop as I knew it would have a large seed base. Here is the magnet url:
> magnet:?xt=urn:btih:89EBCCD43FA8F75F8439896EA5211EA60E041A4F&dn=Adobe%20Photoshop%20CC%202015%20(20150529.r.88)%20(32%2B64Bit)%20%2B%20Crack&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2F47.ip-51-68-199.eu%3A6969%2Fannounce
> 
> This torrent is still able to download despite your script.

Hi there. Thanks for using this script. This is just a personal script im using to block torrent in ubuntu.
We are using rutorrent interface and this script are working perfectly. User cannot download torrent because all website , udp and etc has been blocking. 👯

**Comment by Heclalava** [comment]
I actually forked the script and added a lot more trackers and torrent websites to the blocklist, and I also modified the script to remove duplicates from the hosts file as well as put in my crontab to run daily to update the hosts file. It actually works well now.

**Comment by mrlongshen** [comment]
> I actually forked the script and added a lot more trackers and torrent websites to the blocklist, and I also modified the script to remove duplicates from the hosts file as well as put in my crontab to run daily to update the hosts file. It actually works well now.

ok. Cool. Enjoy it. 👍
